package io.github.sweetpark.apm.interceptor.jpa;

import io.github.sweetpark.apm.core.config.ApmProperties;
import io.github.sweetpark.apm.core.context.TraceContextHolder;
import io.github.sweetpark.apm.core.enums.LogMarker;
import io.github.sweetpark.apm.core.sql.SqlTraceContext;
import io.github.sweetpark.apm.core.sql.SqlTraceContextHolder;
import io.github.sweetpark.apm.core.support.util.SQLUtil;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/** JDBC Statement를 프록시하여 일반 SQL 실행을 추적하는 래퍼 클래스입니다. */
public class ApmProxyStatement implements Statement {

  private static final Logger logger = LoggerFactory.getLogger("ApmLog");

  private final Statement delegate;
  private final ApmProperties properties;

  public ApmProxyStatement(Statement delegate, ApmProperties properties) {
    this.delegate = delegate;
    this.properties = properties;
  }

  private void trackExecution(String sql, long startMs, boolean isError) {
    if (SqlTraceContextHolder.isMyBatisActive()) {
      return;
    }

    long elapsed = System.currentTimeMillis() - startMs;
    String sqlId = extractSqlId(sql);

    ApmProperties props = properties != null ? properties : new ApmProperties();
    SqlTraceContext ctx = SqlTraceContextHolder.get();

    if (ctx != null) {
      int maxCount = props.getLimit().getMaxSqlCount();
      int maxDetailCount = props.getLimit().getMaxSqlDetailCount();

      boolean isFull = ctx.isFull(maxCount);
      if (isFull && isError) {
        ctx.removeOldestNormal();
        isFull = false;
      }

      if (isFull) {
        ctx.addOmitted();
      } else {
        boolean includeDetail = isError || !ctx.isDetailFull(maxDetailCount);
        String normalizedSql =
            includeDetail ? SQLUtil.normalizeSql(sql, props.getLimit().getMaxSqlLength()) : null;
        ctx.add(sqlId, normalizedSql, null, elapsed, isError, includeDetail);
      }
    }

    TraceContextHolder.addBreadcrumb(isError ? "SQL_ERROR" : "SQL", sqlId + " " + elapsed + "ms");

    if (ctx != null) {
      int callCount = ctx.incrementCallCount(sqlId);
      int threshold = props.getLimit().getN1DetectionThreshold();

      if (callCount == threshold) {
        logger.warn(
            LogMarker.N1_QUERY.marker(),
            "trace_id={} sql_id={} call_count={} possible N+1 detected",
            TraceContextHolder.traceId(),
            sqlId,
            callCount);
      }
    }
  }

  private String extractSqlId(String sql) {
    if (sql == null || sql.isBlank()) {
      return "JDBC:QUERY";
    }
    String normalized = sql.replaceAll("\\s+", " ").trim();
    String[] tokens = normalized.split(" ");
    if (tokens.length >= 3) {
      return (tokens[0] + " " + tokens[1] + " " + tokens[2]).toUpperCase();
    }
    return tokens[0].toUpperCase();
  }

  @Override
  public ResultSet executeQuery(String sql) throws SQLException {
    long start = System.currentTimeMillis();
    boolean error = false;
    try {
      return delegate.executeQuery(sql);
    } catch (SQLException e) {
      error = true;
      throw e;
    } finally {
      trackExecution(sql, start, error);
    }
  }

  @Override
  public int executeUpdate(String sql) throws SQLException {
    long start = System.currentTimeMillis();
    boolean error = false;
    try {
      return delegate.executeUpdate(sql);
    } catch (SQLException e) {
      error = true;
      throw e;
    } finally {
      trackExecution(sql, start, error);
    }
  }

  @Override
  public boolean execute(String sql) throws SQLException {
    long start = System.currentTimeMillis();
    boolean error = false;
    try {
      return delegate.execute(sql);
    } catch (SQLException e) {
      error = true;
      throw e;
    } finally {
      trackExecution(sql, start, error);
    }
  }

  @Override
  public int[] executeBatch() throws SQLException {
    long start = System.currentTimeMillis();
    boolean error = false;
    try {
      return delegate.executeBatch();
    } catch (SQLException e) {
      error = true;
      throw e;
    } finally {
      trackExecution("BATCH_QUERY", start, error);
    }
  }

  @Override
  public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
    long start = System.currentTimeMillis();
    boolean error = false;
    try {
      return delegate.executeUpdate(sql, autoGeneratedKeys);
    } catch (SQLException e) {
      error = true;
      throw e;
    } finally {
      trackExecution(sql, start, error);
    }
  }

  @Override
  public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
    long start = System.currentTimeMillis();
    boolean error = false;
    try {
      return delegate.executeUpdate(sql, columnIndexes);
    } catch (SQLException e) {
      error = true;
      throw e;
    } finally {
      trackExecution(sql, start, error);
    }
  }

  @Override
  public int executeUpdate(String sql, String[] columnNames) throws SQLException {
    long start = System.currentTimeMillis();
    boolean error = false;
    try {
      return delegate.executeUpdate(sql, columnNames);
    } catch (SQLException e) {
      error = true;
      throw e;
    } finally {
      trackExecution(sql, start, error);
    }
  }

  @Override
  public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
    long start = System.currentTimeMillis();
    boolean error = false;
    try {
      return delegate.execute(sql, autoGeneratedKeys);
    } catch (SQLException e) {
      error = true;
      throw e;
    } finally {
      trackExecution(sql, start, error);
    }
  }

  @Override
  public boolean execute(String sql, int[] columnIndexes) throws SQLException {
    long start = System.currentTimeMillis();
    boolean error = false;
    try {
      return delegate.execute(sql, columnIndexes);
    } catch (SQLException e) {
      error = true;
      throw e;
    } finally {
      trackExecution(sql, start, error);
    }
  }

  @Override
  public boolean execute(String sql, String[] columnNames) throws SQLException {
    long start = System.currentTimeMillis();
    boolean error = false;
    try {
      return delegate.execute(sql, columnNames);
    } catch (SQLException e) {
      error = true;
      throw e;
    } finally {
      trackExecution(sql, start, error);
    }
  }

  @Override
  public void close() throws SQLException {
    delegate.close();
  }

  @Override
  public int getMaxFieldSize() throws SQLException {
    return delegate.getMaxFieldSize();
  }

  @Override
  public void setMaxFieldSize(int max) throws SQLException {
    delegate.setMaxFieldSize(max);
  }

  @Override
  public int getMaxRows() throws SQLException {
    return delegate.getMaxRows();
  }

  @Override
  public void setMaxRows(int max) throws SQLException {
    delegate.setMaxRows(max);
  }

  @Override
  public void setEscapeProcessing(boolean enable) throws SQLException {
    delegate.setEscapeProcessing(enable);
  }

  @Override
  public int getQueryTimeout() throws SQLException {
    return delegate.getQueryTimeout();
  }

  @Override
  public void setQueryTimeout(int seconds) throws SQLException {
    delegate.setQueryTimeout(seconds);
  }

  @Override
  public void cancel() throws SQLException {
    delegate.cancel();
  }

  @Override
  public SQLWarning getWarnings() throws SQLException {
    return delegate.getWarnings();
  }

  @Override
  public void clearWarnings() throws SQLException {
    delegate.clearWarnings();
  }

  @Override
  public void setCursorName(String name) throws SQLException {
    delegate.setCursorName(name);
  }

  @Override
  public ResultSet getResultSet() throws SQLException {
    return delegate.getResultSet();
  }

  @Override
  public int getUpdateCount() throws SQLException {
    return delegate.getUpdateCount();
  }

  @Override
  public boolean getMoreResults() throws SQLException {
    return delegate.getMoreResults();
  }

  @Override
  public void setFetchDirection(int direction) throws SQLException {
    delegate.setFetchDirection(direction);
  }

  @Override
  public int getFetchDirection() throws SQLException {
    return delegate.getFetchDirection();
  }

  @Override
  public void setFetchSize(int rows) throws SQLException {
    delegate.setFetchSize(rows);
  }

  @Override
  public int getFetchSize() throws SQLException {
    return delegate.getFetchSize();
  }

  @Override
  public int getResultSetConcurrency() throws SQLException {
    return delegate.getResultSetConcurrency();
  }

  @Override
  public int getResultSetType() throws SQLException {
    return delegate.getResultSetType();
  }

  @Override
  public void addBatch(String sql) throws SQLException {
    delegate.addBatch(sql);
  }

  @Override
  public void clearBatch() throws SQLException {
    delegate.clearBatch();
  }

  @Override
  public boolean getMoreResults(int current) throws SQLException {
    return delegate.getMoreResults(current);
  }

  @Override
  public ResultSet getGeneratedKeys() throws SQLException {
    return delegate.getGeneratedKeys();
  }

  @Override
  public int getResultSetHoldability() throws SQLException {
    return delegate.getResultSetHoldability();
  }

  @Override
  public boolean isClosed() throws SQLException {
    return delegate.isClosed();
  }

  @Override
  public void setPoolable(boolean poolable) throws SQLException {
    delegate.setPoolable(poolable);
  }

  @Override
  public boolean isPoolable() throws SQLException {
    return delegate.isPoolable();
  }

  @Override
  public void closeOnCompletion() throws SQLException {
    delegate.closeOnCompletion();
  }

  @Override
  public boolean isCloseOnCompletion() throws SQLException {
    return delegate.isCloseOnCompletion();
  }

  @Override
  public <T> T unwrap(Class<T> iface) throws SQLException {
    if (iface.isInstance(this)) {
      return iface.cast(this);
    }
    if (iface.isInstance(delegate)) {
      return iface.cast(delegate);
    }
    return delegate.unwrap(iface);
  }

  @Override
  public boolean isWrapperFor(Class<?> iface) throws SQLException {
    return iface.isInstance(this) || iface.isInstance(delegate) || delegate.isWrapperFor(iface);
  }

  @Override
  public Connection getConnection() throws SQLException {
    return delegate.getConnection();
  }
}
